remote_theme: BDHU/minimalist

highlighter: pygments
title: Buddy Assignment Network Tool Repository (BANTR)
descriptionTitle: Description
storyTitle: The story of BANTR
howItWorksTitle: How it works
finalCodeTitle: Final Code
# alternative description: Creating a python program to assist in the process of matching incoming freshman and upper classmen based on their interests for the Gibson Ek Buddy Program.
livereload: True

