remote_theme: BDHU/minimalist
highlighter: rogue
title: Table of Contents
descriptionTitle: Description
storyTitle: The story of BANTR
defineTitle: *Define* statement
howItWorksTitle: How it works
sampleInputTitle: Sample input
sampleOutputTitle: Sample output
finalCodeTitle: Final code
# alternative description: Creating a python program to assist in the process of matching incoming freshman and upper classmen based on their interests for the Gibson Ek Buddy Program.
livereload: True

